name: dist

on:
  push:

jobs:
  sources:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev python3-build
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make distcheck
    - uses: actions/upload-artifact@v7
      with:
        name: sources
        path: librawstor-*.tar.gz
        if-no-files-found: error

  deb-librawstor:
    needs: sources

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev debhelper build-essential
    - uses: actions/download-artifact@v8
      with:
        name: sources
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        export LIBRAWSTOR=${LIBRAWSTOR_TAR%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: configure
      run: |
        tar -xzf ${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure --without-python3 --disable-ost-backend
    - name: dpkg-buildpackage
      run: |
        cd ${LIBRAWSTOR}
        mkdir debian
        mkdir debian/source
        cp deb/librawstor/control debian
        cp deb/librawstor/compat debian
        cp deb/librawstor/changelog debian
        cp deb/librawstor/format debian/source
        cp deb/librawstor/librawstor.install debian
        cp deb/librawstor/librawstor-dev.install debian
        cp deb/librawstor/rawstor-ost.install debian
        cp deb/librawstor/rawstor-ost.postinst debian
        cp deb/librawstor/rawstor-ost.prerm debian
        cp deb/librawstor/rules debian
        cp etc/systemd/system/rawstor-ost.service debian
        cp COPYING debian/copyright
        dpkg-buildpackage -us -uc
    - name: ls
      run: |
        for i in librawstor_*.deb librawstor-dev_*.deb rawstor-ost_*.deb; do \
          echo dpkg --contents $i; \
          dpkg --contents $i; \
        done
    - uses: actions/upload-artifact@v7
      with:
        name: librawstor.deb
        path: |
          librawstor_*.deb
          librawstor-dev_*.deb
          rawstor-ost_*.deb
        if-no-files-found: error

  deb-python3-rawstor:
    needs:
    - sources
    - deb-librawstor

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev python3-build debhelper dh-python python3-all-dev build-essential pkg-config
    - uses: actions/download-artifact@v8
    - name: install librawstor
      run: |
        sudo apt install -y ./librawstor.deb/librawstor_*.deb
        sudo apt install -y ./librawstor.deb/librawstor-dev_*.deb
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(cd sources && ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        export LIBRAWSTOR=${LIBRAWSTOR_TAR%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: make
      run: |
        tar -xzf sources/${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure
    - name: dpkg-buildpackage
      run: |
        cd ${LIBRAWSTOR}/pyrawstor
        mkdir debian
        mkdir debian/source
        cp ../deb/python3-rawstor/control debian
        cp ../deb/python3-rawstor/compat debian
        cp ../deb/python3-rawstor/changelog debian
        cp ../deb/python3-rawstor/format debian/source
        cp ../deb/python3-rawstor/rules debian
        cp ../COPYING debian/copyright
        dpkg-buildpackage -us -uc
        mv ../python*-rawstor_*.deb ${GITHUB_WORKSPACE}
    - name: ls
      run: |
        for i in python*-rawstor_*.deb; do \
          echo dpkg --contents $i; \
          dpkg --contents $i; \
        done
    - uses: actions/upload-artifact@v7
      with:
        name: python3-rawstor.deb
        path: python*-rawstor_*.deb
        if-no-files-found: error

  deb-install:
    needs:
    - deb-librawstor
    - deb-python3-rawstor

    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v8
    - name: install-librawstor
      run: sudo apt install -y ./librawstor.deb/librawstor_*.deb
    - name: test-librawstor
      run: rawstor-cli --version
    - name: install-rawstor-ost
      run: |
        sudo apt install -y ./librawstor.deb/rawstor-ost_*.deb
        sudo systemctl start rawstor-ost.service
    - name: test-rawstor-ost
      run: |
        rawstor-ost --version
        rawstor-cli create --size=1M --location=ost://127.0.0.1:7777
        rawstor-cli list --location=ost://127.0.0.1:7777
    - name: install-python3-rawstor
      run: sudo apt install -y ./python3-rawstor.deb/python*-rawstor_*.deb
    - name: test-python3-rawstor
      run: python -c "import rawstor; print(list(rawstor.Location('ost://127.0.0.1:7777/'))); print('OK')"

  rpm-librawstor:
    needs: sources

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev rpm rpmlint python3-build
    - name: setuptree
      run: |
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
    - uses: actions/download-artifact@v8
      with:
        name: sources
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        export LIBRAWSTOR=${LIBRAWSTOR_TAR%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: configure
      run: |
        tar -xzf ${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure --prefix=${HOME}/rpmbuild/BUILD --without-python3
    - name: rpmbuild
      run: |
        cp ${LIBRAWSTOR}/rpm/librawstor.spec ~/rpmbuild/SPECS
        cp 
        cp ${LIBRAWSTOR_TAR_GZ} ~/rpmbuild/SOURCES
        rpmlint -c ${LIBRAWSTOR}/rpm/rpmlintrc ~/rpmbuild/SPECS/librawstor.spec
        rpmbuild -bb ~/rpmbuild/SPECS/librawstor.spec
    - name: ls
      run: |
        for i in ~/rpmbuild/RPMS/x86_64/*.rpm; do \
          echo rpm -qlp $i; \
          rpm -qlp $i; \
        done
    - uses: actions/upload-artifact@v7
      with:
        name: librawstor.rpm
        path: ~/rpmbuild/RPMS/x86_64/*.rpm
        if-no-files-found: error

  release:
    needs:
    - sources
    - deb-librawstor
    - deb-python3-rawstor
    - deb-install
    - rpm-librawstor

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
    - uses: actions/checkout@v7
      with:
        path: librawstor
    - name: fetch tags
      run: |
        cd librawstor
        git fetch --tags --force origin
    - name: import GPG public keys
      run: gpg --import librawstor/.github/gpg-keys/*.asc
    - name: verify
      run: |
        cd librawstor
        git verify-tag ${{ github.ref_name }}
    - uses: actions/download-artifact@v8
      with:
        path: ./artifacts
    - uses: softprops/action-gh-release@v3
      with:
        working_directory: ./artifacts
        files: |
          librawstor.deb/*
          python3-rawstor.deb/*
          librawstor.rpm/*
          sources/*
