name: dist

on:
  push:

jobs:
  sources:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev python3-build
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make distcheck
    - uses: actions/upload-artifact@v7
      with:
        name: sources
        path: librawstor-*.tar.gz
        if-no-files-found: error

  deb-librawstor:
    needs: sources

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev
    - uses: actions/download-artifact@v8
      with:
        name: sources
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: make
      run: |
        tar -xzf ${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure --prefix=${GITHUB_WORKSPACE}/build/librawstor --without-python3
        make -j$(nproc)
        make test
        make install
    - name: dpkg-deb
      run: |
        mkdir ${GITHUB_WORKSPACE}/build/librawstor/DEBIAN
        cp ${LIBRAWSTOR}/deb/librawstor ${GITHUB_WORKSPACE}/build/librawstor/DEBIAN/control
        dpkg-deb --build ${GITHUB_WORKSPACE}/build/librawstor build/${LIBRAWSTOR}.deb
    - uses: actions/upload-artifact@v7
      with:
        name: deb
        path: build/librawstor-*.deb
        if-no-files-found: error

  deb-python3-rawstor:
    needs: sources

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev python3-build
    - uses: actions/download-artifact@v8
      with:
        name: sources
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: make
      run: |
        tar -xzf ${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure --prefix=${GITHUB_WORKSPACE}/build/python3-rawstor
        make -j$(nproc)
        make test
        make -C pyrawstor install
        ls -lhR ${GITHUB_WORKSPACE}/build/python3-rawstor 
    - name: dpkg-deb
      run: |
        mkdir ${GITHUB_WORKSPACE}/build/python3-rawstor/DEBIAN
        cp ${LIBRAWSTOR}/deb/python3-rawstor ${GITHUB_WORKSPACE}/build/python3-rawstor/DEBIAN/control
        dpkg-deb --build ${GITHUB_WORKSPACE}/build/python3-rawstor build/${LIBRAWSTOR}.deb
    - uses: actions/upload-artifact@v7
      with:
        name: deb
        path: build/python3-rawstor-*.deb
        if-no-files-found: error

  deb-install:
    needs:
    - deb-librawstor
    - deb-python3-rawstor

    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v8
      with:
        artifact-ids: deb-librawstor,deb-python3-rawstor
    - name: install-librawstor
      run: |
        sudo apt install -y ./librawstor-*.deb
    - name: test-librastor
      run: |
        rawstor-cli --version
        rawstor-ost --version
    - name: install-python3-rawstor
      run: |
        sudo apt install -y ./python3-rawstor-*.deb
    - name: test-python3-rawstor
      run: |
        python -c "import rawstor; print('OK')"

  rpm:
    needs: sources

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev libgtest-dev python3-build rpm rpmlint
    - name: setuptree
      run: |
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
    - uses: actions/download-artifact@v8
      with:
        name: sources
    - name: env
      run: |
        export LIBRAWSTOR_TAR_GZ=$(ls librawstor-*.tar.gz)
        export LIBRAWSTOR_TAR=${LIBRAWSTOR_TAR_GZ%.*}
        export LIBRAWSTOR=${LIBRAWSTOR_TAR%.*}
        echo "LIBRAWSTOR_TAR_GZ=${LIBRAWSTOR_TAR_GZ}" >> $GITHUB_ENV
        echo "LIBRAWSTOR=${LIBRAWSTOR}" >> $GITHUB_ENV
    - name: configure
      run: |
        tar -xzf ${LIBRAWSTOR_TAR_GZ}
        cd ${LIBRAWSTOR}
        ./configure --prefix=${HOME}/rpmbuild/BUILD
    - name: rpmbuild
      run: |
        cp ${LIBRAWSTOR}/rpm/librawstor.spec ~/rpmbuild/SPECS
        cp ${LIBRAWSTOR_TAR_GZ} ~/rpmbuild/SOURCES
        rpmlint ~/rpmbuild/SPECS/librawstor.spec
        rpmbuild -bb ~/rpmbuild/SPECS/librawstor.spec
    - uses: actions/upload-artifact@v7
      with:
        name: rpm
        path: ~/rpmbuild/RPMS/x86_64/librawstor-*.rpm
        if-no-files-found: error

  release:
    needs:
    - sources
    - deb-librawstor
    - deb-python3-rawstor
    - deb-install
    - rpm

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
    - uses: actions/checkout@v7
      with:
        path: librawstor
    - name: fetch tags
      run: |
        cd librawstor
        git fetch --tags --force origin
    - name: import GPG public keys
      run: gpg --import librawstor/.github/gpg-keys/*.asc
    - name: verify
      run: |
        cd librawstor
        git verify-tag ${{ github.ref_name }}
    - uses: actions/download-artifact@v8
      with:
        path: ./artifacts
    - uses: softprops/action-gh-release@v3
      with:
        working_directory: ./artifacts
        files: |
          deb-librawstor/*
          deb-python3-rawstor/*
          rpm/*
          sources/*
