name: librawstor

on:
  push:
    branches: [ "feat/ci" ]
  pull_request:
    branches: [ "feat/ci" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev
    - uses: actions/checkout@v4
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
