name: release

on:
  push:
    tags:
    - "v*"


jobs:
  verify-tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: fetch all tags
      run: git fetch --tags origin
    - name: verify
      run: git verify-tag ${{ github.ref_name }}
