name: release

on:
  push:
    tags:
    - "v*"


jobs:
  verify-tag:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
    - name: import GPG public keys
      run: gpg --import .github/gpg-keys/*.asc
    - uses: actions/checkout@v4
    - name: fetch all tags
      run: git fetch --tags --force origin
    - name: verify
      run: git verify-tag ${{ github.ref_name }}
